version: 2
jobs:
  build_and_test:
    run: ls -lR ~/Documentos/mootube
    working_directory: ~/Documentos/mootube
    docker:
      - image: php:7.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: apt-get update && apt-get -y install git unzip zlib1g-dev
      - run:
          name: Install PHP Extensions
          command: docker-php-ext-install pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"

      # Dependencies
      - checkout
      - restore_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
      - run: composer install --prefer-dist --no-interaction
      # Force pulling Simple PHPUnit dependencies to be able to cache them as well
      - run: ./vendor/bin/simple-phpunit --version
      - save_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
          paths:
            - '/root/.composer/cache'
            - './vendor'

      # Database
      - run: ./bin/console doctrine:database:create --env=test
      - run: ./bin/console doctrine:schema:create --env=test
      #- run: ./bin/console hautelook_alice:doctrine:fixtures:load --no-interaction

      # To use server:start we need to install pcntl extension
      - run:
          name: Run web server in background
          command: ./bin/console server:run
          background: true

      # Testing
      #- run: ./bin/console lint:yaml app/config
      #- run: ./bin/console lint:twig app/Resources
      - run: ./vendor/bin/simple-phpunit

  deploy:
    working_directory: ~/Documentos/startv2
    docker:
      - image: ansible/ansible:ubuntu1804
        environment:
          ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: pip install --upgrade pip && pip install ansible

      # Dependencies
      - checkout
      - restore_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
      - run: ansible-galaxy install -r ansible/requirements.yml
      - save_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
          paths:
            - '/root/.ansible/roles'

      # Deploy
      - run: echo $ANSIBLE_VAULT_PASS > ./ansible/.vault-pass.txt
      - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini -e --vault-password-file=./ansible/.vault-pass.txt
      - run: rm ./ansible/.vault-pass.txt

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
