---
- name: Set up infrastructure related parameters
  template:
    src: "{{ playbook_dir }}/templates/.env"
    dest: "{{ ansistrano_release_path.stdout }}/.env"
- name: Install composer deps
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
- name: setup permissions directory for var
  file:
    path: "{{ release_var_path }}"
    state: directory
    mode: 0777
    recurse: true
- name: Create DB if not exists
  command: '{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod'
  register: create_db_output
  #changed_when: create_db_output.stdout is not search('already exists. Skipped')
- name: Run migrations
  command: '{{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod'
  register: run_migrations_output
  changed_when: not run_migrations_output.stdout|search('No migrations to execute')
- name: Clear the cache
  command: "{{ release_console_path }} cache:clear --no-warmup --env=prod"
- name: warm up the cache
  command: "{{ release_console_path }} cache:warmup --env=prod"