---
- hosts: aws
  vars_files:
    - ./vars/vars.yml
    - ./vars/deploy_vault.yml
    - ./vars/deploy_vars.yml
  vars:
    ansistrano_deploy_to: "{{ symfony_root_dir }}"
    ansistrano_deploy_via: git # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download
    # Variables used in the Git deployment strategy
    ansistrano_git_repo: "git@github.com:Sayil8/Symfony_articles.git" # Location of the git repository
    ansistrano_git_branch: master # What version of the repository to check out. This can be the full 40-character SHA-1 hash,
    ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"
  roles:
    - ansistrano.deploy